### PR TITLE
Added device capability last update condition

### PR DESCRIPTION
**Pull request by irritanterik**
In advance of firmware version 0.10.4 I added this condition card based on @weejewel his comment in https://github.com/athombv/homey/issues/974.

### CODE REVIEW

**Comment by matjaz** [comment]
Haven't tested, but but it looks great. Thanks!

**Comment by matjaz** [comment]
submitted in app store.

**Comment by irritanterik** [comment]
We're fast!

**Comment by matjaz** [comment]
'`contributors.developers[1].email` is undefined or not a string'

**Comment by matjaz** [comment]
please use cli tool to verify.

**Pull request merged**
